import { AbsoluteFill, interpolate, spring, useCurrentFrame, useVideoConfig, Sequence } from "remotion";
import { UICard } from "../components/UICard";
import { SceneLabel } from "../components/SceneLabel";
import { NeonText } from "../components/NeonText";

// TAB TYPES
const TABS = ["Tasks", "Notes", "Workflow", "Spreadsheet", "API"];

// TASK CARD
const TaskCard = ({
  title, priority, status, delay, frame, fps,
}: {
  title: string; priority: "high" | "medium" | "low"; status: string; delay: number; frame: number; fps: number;
}) => {
  const s = spring({ frame: frame - delay, fps, config: { damping: 200 } });
  const opacity = interpolate(s, [0, 1], [0, 1]);
  const y = interpolate(s, [0, 1], [20, 0]);
  const colors = { high: "#ef4444", medium: "#f59e0b", low: "#22c55e" };
  return (
    <div
      style={{
        opacity,
        transform: `translateY(${y}px)`,
        padding: "12px 14px",
        borderRadius: 12,
        background: "#1c1c1f",
        border: "1px solid #27272a",
        display: "flex",
        flexDirection: "column",
        gap: 8,
        marginBottom: 8,
      }}
    >
      <div style={{ fontFamily: "'Inter', sans-serif", fontSize: 14, fontWeight: 500, color: "#f4f4f5" }}>{title}</div>
      <div style={{ display: "flex", gap: 8, alignItems: "center" }}>
        <span
          style={{
            padding: "2px 8px",
            borderRadius: 6,
            background: `${colors[priority]}20`,
            border: `1px solid ${colors[priority]}50`,
            fontSize: 11,
            color: colors[priority],
            fontFamily: "'Inter', sans-serif",
          }}
        >
          {priority}
        </span>
        <span style={{ fontSize: 11, color: "#71717a", fontFamily: "'Inter', sans-serif" }}>{status}</span>
      </div>
    </div>
  );
};

// KANBAN COLUMN
const KanbanColumn = ({ title, tasks, delay, frame, fps }: {
  title: string;
  tasks: Array<{ title: string; priority: "high" | "medium" | "low"; status: string }>;
  delay: number;
  frame: number;
  fps: number;
}) => {
  const s = spring({ frame: frame - delay, fps, config: { damping: 200 } });
  const opacity = interpolate(s, [0, 1], [0, 1]);
  const y = interpolate(s, [0, 1], [30, 0]);
  return (
    <div style={{ flex: 1, opacity, transform: `translateY(${y}px)` }}>
      <div
        style={{
          fontFamily: "'Inter', sans-serif",
          fontSize: 12,
          fontWeight: 600,
          color: "#71717a",
          textTransform: "uppercase",
          letterSpacing: "0.08em",
          marginBottom: 12,
        }}
      >
        {title} <span style={{ color: "#3f3f46" }}>({tasks.length})</span>
      </div>
      {tasks.map((t, i) => (
        <TaskCard key={i} {...t} delay={delay + i * 6} frame={frame} fps={fps} />
      ))}
    </div>
  );
};

// NOTES PREVIEW
const NotesPreview = ({ frame, fps, startFrame }: { frame: number; fps: number; startFrame: number }) => {
  const localFrame = frame - startFrame;
  const opacity = interpolate(localFrame, [0, 0.3 * fps], [0, 1], { extrapolateRight: "clamp" });
  const lines = [
    "# Alpha Launch Brief",
    "",
    "**Goal:** Ship MVP by Q2 2025",
    "**Stack:** TypeScript, Convex, React Router",
    "",
    "## Key milestones",
    "- [ ] Auth system complete",
    "- [x] Agent runtime stable",
    "- [ ] Public beta launch",
    "",
    "*Generated by HiGantic agent based on task board context.*",
  ];
  const charCount = Math.floor((localFrame / fps) * 60);
  let totalChars = 0;
  return (
    <div style={{ opacity, padding: 24, fontFamily: "'Courier New', monospace", fontSize: 14, color: "#d4d4d8", lineHeight: 1.8 }}>
      {lines.map((line, i) => {
        const prevChars = totalChars;
        totalChars += line.length + 1;
        const visible = Math.max(0, Math.min(line.length, charCount - prevChars));
        const text = line.slice(0, visible);
        const color = line.startsWith("#") ? "#4ade80" : line.startsWith("**") ? "#f4f4f5" : line.startsWith("- [x]") ? "#71717a" : "#d4d4d8";
        return (
          <div key={i} style={{ color, minHeight: 24 }}>
            {text}
            {visible < line.length && charCount > prevChars && (
              <span style={{ color: "#4ade80" }}>|</span>
            )}
          </div>
        );
      })}
    </div>
  );
};

export const WorkspaceScene = () => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();

  // Tab switching: 0-5s=Tasks, 5-10s=Notes, 10-15s=Workflow
  const activeTabIdx = frame < 5 * fps ? 0 : frame < 10 * fps ? 1 : 2;

  const titleOpacity = interpolate(frame, [0, 0.5 * fps], [0, 1], { extrapolateRight: "clamp" });

  const tasksStart = 0;
  const notesStart = Math.round(5 * fps);
  const workflowStart = Math.round(10 * fps);

  return (
    <AbsoluteFill style={{ background: "#09090b" }}>
      <div
        style={{
          position: "absolute",
          inset: 0,
          display: "flex",
          flexDirection: "column",
          padding: "40px 80px",
          gap: 20,
        }}
      >
        {/* Title */}
        <div style={{ opacity: titleOpacity }}>
          <NeonText size={44}>A full workspace, controlled by your agent</NeonText>
        </div>

        {/* Main UI shell */}
        <div style={{ display: "flex", flex: 1, gap: 16, minHeight: 0 }}>
          {/* Sidebar */}
          <div
            style={{
              width: 200,
              background: "#141414",
              borderRadius: 16,
              border: "1px solid #1c1c1f",
              padding: 16,
              display: "flex",
              flexDirection: "column",
              gap: 4,
            }}
          >
            <div style={{ fontFamily: "'Inter', sans-serif", fontSize: 11, color: "#52525b", textTransform: "uppercase", letterSpacing: "0.1em", marginBottom: 8 }}>
              Workspace
            </div>
            {TABS.map((tab, i) => {
              const icons = ["☰", "📝", "⚡", "📊", "🔌"];
              const active = i === activeTabIdx;
              return (
                <div
                  key={tab}
                  style={{
                    padding: "8px 12px",
                    borderRadius: 10,
                    background: active ? "rgba(74,222,128,0.1)" : "transparent",
                    border: active ? "1px solid rgba(74,222,128,0.2)" : "1px solid transparent",
                    fontFamily: "'Inter', sans-serif",
                    fontSize: 13,
                    color: active ? "#4ade80" : "#71717a",
                    display: "flex",
                    alignItems: "center",
                    gap: 8,
                    cursor: "default",
                  }}
                >
                  {icons[i]} {tab}
                </div>
              );
            })}
          </div>

          {/* Content area */}
          <UICard style={{ flex: 1, overflow: "hidden", padding: 0 }}>
            {/* Tab header */}
            <div
              style={{
                padding: "16px 24px",
                borderBottom: "1px solid #1c1c1f",
                display: "flex",
                alignItems: "center",
                gap: 8,
              }}
            >
              <span style={{ fontFamily: "'Inter', sans-serif", fontSize: 16, fontWeight: 600, color: "#f4f4f5" }}>
                {TABS[activeTabIdx]}
              </span>
              <span
                style={{
                  padding: "2px 10px",
                  borderRadius: 6,
                  background: "rgba(74,222,128,0.1)",
                  border: "1px solid rgba(74,222,128,0.25)",
                  fontSize: 11,
                  color: "#4ade80",
                  fontFamily: "'Inter', sans-serif",
                }}
              >
                Agent-managed
              </span>
            </div>

            {/* Tasks Kanban */}
            {activeTabIdx === 0 && (
              <div style={{ padding: 24, display: "flex", gap: 20, height: "calc(100% - 60px)" }}>
                <KanbanColumn
                  title="To Do"
                  tasks={[
                    { title: "Design auth flow", priority: "high", status: "Assigned to agent" },
                    { title: "Write API docs", priority: "medium", status: "Backlog" },
                  ]}
                  delay={Math.round(0.3 * fps)}
                  frame={frame}
                  fps={fps}
                />
                <KanbanColumn
                  title="In Progress"
                  tasks={[
                    { title: "Build dashboard UI", priority: "high", status: "Agent working..." },
                  ]}
                  delay={Math.round(0.5 * fps)}
                  frame={frame}
                  fps={fps}
                />
                <KanbanColumn
                  title="Done"
                  tasks={[
                    { title: "Set up Convex schema", priority: "low", status: "Completed" },
                    { title: "Configure Clerk auth", priority: "medium", status: "Completed" },
                  ]}
                  delay={Math.round(0.7 * fps)}
                  frame={frame}
                  fps={fps}
                />
              </div>
            )}

            {/* Notes */}
            {activeTabIdx === 1 && (
              <NotesPreview frame={frame} fps={fps} startFrame={notesStart} />
            )}

            {/* Workflow preview */}
            {activeTabIdx === 2 && (
              <div style={{ padding: 24, opacity: interpolate(frame - workflowStart, [0, 0.4 * fps], [0, 1], { extrapolateRight: "clamp" }) }}>
                <div style={{ display: "flex", flexDirection: "column", gap: 12, maxWidth: 500 }}>
                  {[
                    { icon: "⚡", label: "Trigger: task.created", color: "#8b5cf6" },
                    { icon: "→", label: "", color: "#3f3f46", arrow: true },
                    { icon: "✉️", label: "Action: Send email notification", color: "#3b82f6" },
                    { icon: "→", label: "", color: "#3f3f46", arrow: true },
                    { icon: "🔔", label: "Action: Slack message to #team", color: "#f59e0b" },
                    { icon: "→", label: "", color: "#3f3f46", arrow: true },
                    { icon: "📝", label: "Action: Add note summary", color: "#4ade80" },
                  ].map((item, i) => {
                    if (item.arrow) {
                      return (
                        <div key={i} style={{ paddingLeft: 20, color: "#3f3f46", fontSize: 20 }}>↓</div>
                      );
                    }
                    const delay2 = Math.round((workflowStart + i * 8) / 1);
                    const s = spring({ frame: frame - (workflowStart + i * 8), fps, config: { damping: 200 } });
                    const op = interpolate(s, [0, 1], [0, 1]);
                    return (
                      <div
                        key={i}
                        style={{
                          opacity: op,
                          transform: `translateX(${interpolate(s, [0, 1], [-20, 0])}px)`,
                          padding: "12px 16px",
                          borderRadius: 12,
                          background: `${item.color}15`,
                          border: `1px solid ${item.color}40`,
                          display: "flex",
                          alignItems: "center",
                          gap: 12,
                          fontFamily: "'Inter', sans-serif",
                          fontSize: 14,
                          color: "#f4f4f5",
                        }}
                      >
                        <span>{item.icon}</span>
                        {item.label}
                      </div>
                    );
                  })}
                </div>
              </div>
            )}
          </UICard>
        </div>
      </div>
      <SceneLabel text="Agent Workspace" />
    </AbsoluteFill>
  );
};
